my_file = open('file_2.txt', 'r')
content = my_file.read()
print(f'Сщдержимое файла: \n {content}')
my_file = open('file_2.txt', 'r')
content = my_file.readlines()
print(f'колличество строк в файле - {len(content)}')
my_file = open('file_2.txt', 'r')
content = my_file.readlines()
for i in range(len(content)):
    print(f'Колличество символов {i + 1} - строки {len(content[i])}')
my_file = open('file_2.txt', 'r')
content = my_file.read()
content = content.split()
print(f'Общее колличество слов - {len(content)}')
my_file.close()